### ISSUE TITLE
Suggestion: Applying for Academic Data Camp Access through Hertie?

### ISSUE THREAD

**Issue by bcichocka** [mhaber/HertieDataScience#6]
I just noticed that it was possible to get free access to other courses, beyond the free Intro to R course, on data camp provided we were signed up through the classroom mode by someone at Hertie at https://www.datacamp.com/groups/education .The application seems pretty easy and feasible. Perhaps this would be of use to a number of people in the class as supplementary material? 

Beata

**Comment by mhaber** [comment]
This is a great idea! I signed our course up and you should be able to enroll using the following link: https://www.datacamp.com/groups/c0152abc1bd5a1dd85e3d8a66d7ababe9ec7d965/invite

**Comment by krisbest** [comment]
I tried to join through this link and got an error message: "You are not allowed to join this group without an invitation." Has anyone else encountered the same error?

**Comment by bcichocka** [comment]
Thank you for applying for us! However, I do have this message as well.

**Comment by nadinai** [comment]
Hi everyone,
I also received an email with an invitation to join. I followed it and everything seems to work. Look in your hertie inbox for the invitation.
